### ISSUE TITLE
Typescript ou Javascript?

### ISSUE THREAD

**Issue by FabriDamazio** [Ada-Code-Studio/AdaCodeStudio.React#1]
Gostaria de saber o ponto de vista de vocês.

**Comment by johnataa** [comment]
Acredito que seja mais uma questão de gosto. A uns dois anos atrás era mais complicado um projeto React com TypeScript, e mesmo assim era possível. Atualmente ficou muito mais acessível e fácil de se trabalhar com isso. O React inteiro tem suporte pra TS, as libs mais conhecidas tbm tem suporte pra TS ou eh feita em TS mesmo. Talvez algumas libs não tão populares sejam carentes das definições de tipos para poder usar com TypeScript. Porém, para esse problema temos um [projeto open source](https://github.com/DefinitelyTyped/DefinitelyTyped) que a comunidade alimenta com as definições de tipos, e é uma mão na roda.

**Comment by diguifi** [comment]
Eu voto em TS sendo o principal motivo, o mais óbvio: type checking.  
Mas vale considerar também interfaces, enums e modularização simples.

JS é bacana também mas, eu acho, que pra ter um produto final com qualidade no js é preciso mais "esforço" (da pra forjar um "type checking" com libs, da pra fazer uns enums migué, da até pra trabalhar bem com orientação a objeto se quiser, usando sintaxe de classes, tem até "extends").

Pela facilidade "out of the box" de gerar um produto com qualidade eu escolheria TS

**Comment by johnataa** [comment]
Concordo com você @diguifi! Sempre tenho a sensação de que o projeto fica mais organizado e menos suscetível a erros bobos (que talvez seriam pegos pelo JS em tempo de execução). Bem como disse, o TS parece oferecer uma facilidade maior, reduzindo o esforço necessário para trazer um produto final com qualidade.

**Comment by FabriDamazio** [comment]
@johnataa  e @diguifi  o tempalte do[ create react app](https://create-react-app.dev/docs/adding-typescript/) atende as necessidades iniciais?

**Comment by johnataa** [comment]
Quais sao as necessidades iniciais @FabriDamazio?

**Comment by FabriDamazio** [comment]
> Quais são as necessidades iniciais @FabriDamazio?

Landing page seria o primordial para termos disponíveis as informações básicas da plataforma.

Logo depois autenticação e registro.

Ou seja, o básico do básico.

**Comment by johnataa** [comment]
Atende as necessidades com certeza!

**Comment by zeyuri** [comment]
Opa,

Qualquer projeto que vai ter um tempo de desenvolvimento mais a longo se beneficia de Typescript, então acho que é uma escolha natural, principalmente no quesito de dev experience.

Agora sobre utilizar o create-react-app eu tenho minhas dúvidas se ele atende por questões de SEO e Server Side Rendering. Uma landing page vai precisar de necessariamente de bom desempenho em SEO e se fosse client-side não daria bom.

**Comment by FabriDamazio** [comment]
> Opa,
> 
> Qualquer projeto que vai ter um tempo de desenvolvimento mais a longo se beneficia de Typescript, então acho que é uma escolha natural, principalmente no quesito de dev experience.
> 
> Agora sobre utilizar o create-react-app eu tenho minhas dúvidas se ele atende por questões de SEO e Server Side Rendering. Uma landing page vai precisar de necessariamente de bom desempenho em SEO e se fosse client-side não daria bom.

Uma pergunta: seria possível deixar apenas a landing page server side e todo resto client side?

**Comment by johnataa** [comment]
Acho que com esse foco no desempenho em SEO, para termos uma boa indexação do Google devemos partir para uma outra abordagem ao invés de apenas usar o React.

**Comment by zeyuri** [comment]
Yep, acho que deveriamos considerar o [NextJS](https://nextjs.org/showcase). É um framework focado em serverside rendering que produz aplicativos isomórficos hibridos e possibilita num mesmo projeto páginas completamentes estáticas e páginas renderizadas renderizadas no server.

**Comment by FabriDamazio** [comment]
> Yep, acho que deveriamos considerar o [NextJS](https://nextjs.org/showcase). É um framework focado em serverside rendering que produz aplicativos isomórficos hibridos e possibilita num mesmo projeto páginas completamentes estáticas e páginas renderizadas no server.

Me parece ótimo. Além disso da pra usar com TS. Eu fecho com o NextJS. Se os senhores concordarem podemos criar a issue para a arquitetura inicial do projeto.

**Comment by johnataa** [comment]
NextTS então? Parece favorável para mim!

**Comment by FabriDamazio** [comment]
@zeyuri @johnataa @diguifi 
Temos um vencedor, vamos de [NextJs com Typescript!](https://nextjs.org/docs/basic-features/typescript)
